### ISSUE TITLE
In contracten zoomt CRSview niet naar betreffende contract ofschoon afdelingen aanwezig zijn

### ISSUE THREAD

**Issue by willempeters** [IDgis/geoide-vfp-issues#6]

**Comment by willempeters** [comment]
Hoi Evert Jan,

 

Kun je mij nog even de link sturen zodat ik op de online testversie kan komen. Ik wil nog even een paar uurtjes testen.

 

Willem

 

Van: Evert Jan Meulenkamp [mailto:notifications@github.com] 
Verzonden: vrijdag 9 januari 2015 10:56
Aan: IDgis/CRS2
CC: willempeters
Onderwerp: Re: [CRS2] In contracten zoomt CRSview niet naar betreffende contract ofschoon afdelingen aanwezig zijn (#6)

 

Closed #6 <https://github.com/IDgis/CRS2/issues/6> .

**Comment by ejmeulenkamp** [comment]
Hoi Willem,

De laatst bij mij bekende gegevens waarmee je in kunt loggen op de testserver zijn:

Adres voor verbinding met extern bureaublad: test.crs2.nl
Gebruikersnaam: brabant
Wachtwoord: h28f94P2

Ik weet niet of je het wachtwoord al gewijzigd hebt of moest wijzigen. Hoop dat het lukt. Anders moet je Herman even vragen om je opnieuw toegang te verlenen. IDgis beheert de toegang tot de server.

Met vriendelijke groet,
Meulenkamp Automatisering


Evert Jan Meulenkamp
Tel: (074) 291 76 94
Fax: (074) 250 39 82

**Comment by willempeters** [comment]
Ok bedankt,

Ik ga zo meteen proberen.

Willem

 

Van: Evert Jan Meulenkamp [mailto:notifications@github.com] 
Verzonden: maandag 16 februari 2015 10:53
Aan: IDgis/CRS2
CC: willempeters
Onderwerp: Re: [CRS2] In contracten zoomt CRSview niet naar betreffende contract ofschoon afdelingen aanwezig zijn (#6)

 

Hoi Willem,

De laatst bij mij bekende gegevens waarmee je in kunt loggen op de testserver zijn:

Adres voor verbinding met extern bureaublad: test.crs2.nl
Gebruikersnaam: brabant
Wachtwoord: h28f94P2

Ik weet niet of je het wachtwoord al gewijzigd hebt of moest wijzigen. Hoop dat het lukt. Anders moet je Herman even vragen om je opnieuw toegang te verlenen. IDgis beheert de toegang tot de server.

Met vriendelijke groet,
Meulenkamp Automatisering


Evert Jan Meulenkamp
Tel: (074) 291 76 94
Fax: (074) 250 39 82
